/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.fragment;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f020027;
        public static final int coordinatorLayoutStyle = 0x7f02006f;
        public static final int font = 0x7f020085;
        public static final int fontProviderAuthority = 0x7f020087;
        public static final int fontProviderCerts = 0x7f020088;
        public static final int fontProviderFetchStrategy = 0x7f020089;
        public static final int fontProviderFetchTimeout = 0x7f02008a;
        public static final int fontProviderPackage = 0x7f02008b;
        public static final int fontProviderQuery = 0x7f02008c;
        public static final int fontStyle = 0x7f02008d;
        public static final int fontVariationSettings = 0x7f02008e;
        public static final int fontWeight = 0x7f02008f;
        public static final int keylines = 0x7f0200a1;
        public static final int layout_anchor = 0x7f0200a8;
        public static final int layout_anchorGravity = 0x7f0200a9;
        public static final int layout_behavior = 0x7f0200aa;
        public static final int layout_dodgeInsetEdges = 0x7f0200d4;
        public static final int layout_insetEdge = 0x7f0200dd;
        public static final int layout_keyline = 0x7f0200de;
        public static final int statusBarBackground = 0x7f02011d;
        public static final int ttcIndex = 0x7f020150;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f04004a;
        public static final int notification_icon_bg_color = 0x7f04004b;
        public static final int ripple_material_light = 0x7f040056;
        public static final int secondary_text_default_material_light = 0x7f040058;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f05004b;
        public static final int compat_button_inset_vertical_material = 0x7f05004c;
        public static final int compat_button_padding_horizontal_material = 0x7f05004d;
        public static final int compat_button_padding_vertical_material = 0x7f05004e;
        public static final int compat_control_corner_material = 0x7f05004f;
        public static final int compat_notification_large_icon_max_height = 0x7f050050;
        public static final int compat_notification_large_icon_max_width = 0x7f050051;
        public static final int notification_action_icon_size = 0x7f05005b;
        public static final int notification_action_text_size = 0x7f05005c;
        public static final int notification_big_circle_margin = 0x7f05005d;
        public static final int notification_content_margin_start = 0x7f05005e;
        public static final int notification_large_icon_height = 0x7f05005f;
        public static final int notification_large_icon_width = 0x7f050060;
        public static final int notification_main_column_padding_top = 0x7f050061;
        public static final int notification_media_narrow_margin = 0x7f050062;
        public static final int notification_right_icon_size = 0x7f050063;
        public static final int notification_right_side_padding_top = 0x7f050064;
        public static final int notification_small_icon_background_padding = 0x7f050065;
        public static final int notification_small_icon_size_as_large = 0x7f050066;
        public static final int notification_subtext_size = 0x7f050067;
        public static final int notification_top_pad = 0x7f050068;
        public static final int notification_top_pad_large_text = 0x7f050069;
    }
    public static final class drawable {
        private drawable() {}

        public static final int notification_action_background = 0x7f060081;
        public static final int notification_bg = 0x7f060082;
        public static final int notification_bg_low = 0x7f060083;
        public static final int notification_bg_low_normal = 0x7f060084;
        public static final int notification_bg_low_pressed = 0x7f060085;
        public static final int notification_bg_normal = 0x7f060086;
        public static final int notification_bg_normal_pressed = 0x7f060087;
        public static final int notification_icon_background = 0x7f060088;
        public static final int notification_template_icon_bg = 0x7f060089;
        public static final int notification_template_icon_low_bg = 0x7f06008a;
        public static final int notification_tile_bg = 0x7f06008b;
        public static final int notify_panel_notification_icon_bg = 0x7f06008c;
    }
    public static final class id {
        private id() {}

        public static final int action_container = 0x7f07000e;
        public static final int action_divider = 0x7f070010;
        public static final int action_image = 0x7f070011;
        public static final int action_text = 0x7f070017;
        public static final int actions = 0x7f070018;
        public static final in